# Generated by Django 2.2.5 on 2021-05-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='dis',
            field=models.BooleanField(default=False),
        ),
    ]
