# Generated by Django 2.2.5 on 2021-05-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_imagemodel_dis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='dis',
        ),
    ]
